version: '3.5'

services:
  prometheus:
    image: registry.services.alin.be/prometheus-alin:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - traefik-net

  node-exporter:
    image: registry.services.alin.be/node-exporter-alin:v1
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=9100
        - traefik.frontend.rule=Host:node-exporter.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro,rslave
        - /etc/hostname:/etc/host_hostname
    environment:
        - HOST_HOSTNAME=/etc/host_hostname
    networks:
      - traefik-net
    command: --path.procfs /host/proc --path.sysfs /host/sys --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)" --collector.textfile.directory /etc/node-exporter/

  alertmanager:
    image: registry.services.alin.be/alertmanager-alin:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=9093
        - traefik.frontend.rule=Host:alertmanager.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    networks:
        - traefik-net
    command: --web.external-url="http://alertmanager.services.alin.be/" --config.file="/etc/alertmanager/config.yml"

  blackbox:
    image: registry.services.alin.be/blackbox-alin:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=9115
        - traefik.frontend.rule=Host:blackbox.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    networks:
      - traefik-net

  prometheus-nginx:
    image: registry.services.alin.be/prometheus-nginx-alin:v1
    depends_on: 
      - prometheus
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:prometheus.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    networks:
      - traefik-net

networks:
  traefik-net:
    external:
      name: traefik-net
