groups:
-  name: my-group-name
   rules:
   - alert: TargetDown
     expr: up == 0
     for: 2m
     labels:
       severity: critical
     annotations:
       description: "Target down {{ $labels.instance }} / Job: {{ $labels.job }} / Value : {{ .Value }}"
